# ---------- Builder stage ----------
    FROM node:20-alpine AS builder

    WORKDIR /app
    
    COPY package*.json ./
    RUN npm ci
    
    COPY tsconfig.json ./
    COPY src ./src
    
    RUN npm run build
    
    
    # ---------- Runtime stage -----------
    FROM node:20-alpine
    
    WORKDIR /app
    
    COPY package*.json ./
    RUN npm ci --only=production
    
    COPY --from=builder /app/dist ./dist
    
EXPOSE 6969
ENV PORT=6969
    
    CMD ["node", "dist/index.js"]
    